notifications:
  email: false

language: node_js

node_js:
  - 'stable'
  - '0.12'

script:
  - npm run build

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
